language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-23.0.2
    - android-22
    - extra-android-support
    - extra-android-m2repository
    
    licenses:
    - '.+'
notifications:
  email: false
  
before_install:
 - chmod +x gradlew
 
script: ./gradlew clean
