language: android
jdk: oraclejdk7

android:
  components:
    - tools
    # The BuildTools version we are using for our project
    - build-tools-23.0.2
    # The SDK version used to compile your project
    - android-23
    - extra-android-support
    - extra-android-m2repository

  licenses:
    - '.+'
notifications:
  email: false
  
before_install:
 - chmod +x gradlew
 
script: ./gradlew clean
