language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-support
    - extra-android-m2repository

  licenses:
    - '.+'
notifications:
  email: false
  
before_install:
 - chmod +x gradlew
 
script: ./gradlew clean
